const cards = [
  {id:'ACC001',name:'黑雲杉',en:'Black Spruce',latin:'Picea mariana',image:'ACC001 黑雲杉.png',energy:'穩定型',element:'土',chakra:'根輪',keywords:['安全感','穩定','勇氣','信任','重新開始','內在力量'],gift:'冷靜判斷、沉穩可靠，擁有在混亂中穩住局面的力量。',shadow:'你可能正承受長期高壓，習慣獨自扛起責任，也不太願意求助。',breakthrough:'放慢腳步，建立穩定生活節奏；接受支持並不會減損你的力量。',message:'當你穩住自己，生命自然會為你開路。',affirm:'我深深扎根於自己的力量之中，也願意接納支持。'},
  {id:'ACC002',name:'沒藥',en:'Myrrh',latin:'Commiphora myrrha',image:'ACC002 沒藥.png',energy:'沉穩型',element:'土',chakra:'根輪',keywords:['沉靜','療癒','智慧','穩定','放下','內在力量'],gift:'你的成熟與洞察，讓你能看懂表象之下真正發生的事。',shadow:'過去的經驗仍在牽動你；為了保護自己，你可能壓抑感受、抗拒改變。',breakthrough:'勇敢說出真實感受，整理該被告別的過往，為新的可能騰出空間。',message:'放下並不是失去，而是讓生命有空間迎接新的禮物。',affirm:'我接納生命所有歷程，並在其中找到智慧與平靜。'},
  {id:'ACC003',name:'月桂',en:'Laurel',latin:'Laurus nobilis',image:'ACC003 月桂.png',energy:'活化型',element:'風',chakra:'喉輪',keywords:['智慧','勇氣','專注','榮耀','自信','洞察'],gift:'你此刻思路清晰，具備做決定、帶領自己向前的能力。',shadow:'完美標準與害怕失敗的心，可能讓你反覆思量、遲遲不敢行動。',breakthrough:'相信自己的價值，做出一直延後的重要決定；允許第一步不完美。',message:'真正的勝利，是超越昨天的自己。',affirm:'我相信自己的智慧，勇敢迎接每一個挑戰。'},
  {id:'ACC004',name:'甜茴香',en:'Fennel Sweet',latin:'Foeniculum vulgare var. dulce',image:'ACC004 甜茴香.png',energy:'活力型',element:'火',chakra:'太陽神經叢',keywords:['自信','釋放','豐盛','行動力','創造力'],gift:'你的熱情與生命力正在甦醒，能鼓舞自己，也能照亮身邊的人。',shadow:'急於看見成果，容易讓你抓緊控制、忽略休息，甚至害怕偏離計畫。',breakthrough:'一次只專注最重要的一件事，在行動中保留彈性，信任生命的節奏。',message:'真正的力量，來自穩定而非急躁。',affirm:'我相信自己的力量，並允許生命自然展開。'},
  {id:'ACC005',name:'玫瑰',en:'Rose',latin:'Rosa × damascena',image:'ACC005 玫瑰.png',energy:'滋養型',element:'水',chakra:'心輪',keywords:['愛','柔軟','自我價值','包容','優雅','療癒'],gift:'你有細膩的感受力，懂得創造美、連結與溫柔的支持。',shadow:'你可能把別人的需要放在自己之前，透過付出換取認可，心也因此容易受傷。',breakthrough:'先照顧自己，坦白說出需求並設立界線；練習安心接受別人的照顧。',message:'你不必證明值得被愛；你的存在本身就有價值。',affirm:'我接納真實的自己，以愛與柔軟走向適合我的道路。'},
  {id:'ACC006',name:'岩蘭草',en:'Vetivert',latin:'Chrysopogon zizanioides',image:'ACC006 岩蘭草.png',energy:'接地型',element:'土',chakra:'根輪',keywords:['安定','耐心','扎根','韌性','安全感','沉靜'],gift:'你可靠而務實，能承接複雜局面，在雜訊裡守住自己的中心。',shadow:'害怕失控可能使你固守熟悉方式，把壓力悶在心裡，誤以為不變就是安全。',breakthrough:'回到身體與呼吸，從一個能掌握的小步驟開始調整，讓穩定也保有流動。',message:'當你回到身體與呼吸，答案會從安定中浮現。',affirm:'我接納真實的自己，以安定與耐心走向適合我的道路。'},
  {id:'ACC007',name:'松樹',en:'Pine',latin:'Pinus sylvestris',image:'ACC007 松樹.png',energy:'淨化型',element:'風',chakra:'心輪',keywords:['清新','勇氣','復原','空間','希望','行動'],gift:'你有強韌的恢復力與向前動能，能為停滯帶來清新的方向。',shadow:'你可能急著振作，用忙碌遮住疲憊；一再逞強，反而失去呼吸的空間。',breakthrough:'清理不再必要的行程與負擔，讓休息成為前進的一部分，再選一件真正重要的事。',message:'清理不再需要的負擔，你會重新看見前方的路。',affirm:'我接納真實的自己，以清新與勇氣走向適合我的道路。'},
  {id:'ACC008',name:'苦橙葉',en:'Petitgrain',latin:'Citrus × aurantium',image:'ACC008 苦橙葉.png',energy:'調和型',element:'風',chakra:'心輪',keywords:['彈性','平衡','釋放','樂觀','連結','重整'],gift:'你善於協調、適應力強，能在理性與感性之間找回平衡。',shadow:'你可能為了避免衝突而延後表態，將真實感受藏起來，也容易落入討好。',breakthrough:'先說出一個真實而溫和的需求，讓和諧不再以委屈自己為代價。',message:'當你不再勉強迎合，真正的和諧才會靠近。',affirm:'我接納真實的自己，以彈性與平衡走向適合我的道路。'},
  {id:'ACC009',name:'永久花',en:'Helichrysum',latin:'Helichrysum italicum',image:'ACC009 永久花.png',energy:'修復型',element:'火',chakra:'太陽神經叢',keywords:['復原','希望','勇敢','更新','完整','釋懷'],gift:'你能在挫折之後重新整合，並看見傷痕背後的意義與希望。',shadow:'過去的不公平或受傷經驗仍讓你警覺，可能因此緊抓舊傷、不易信任。',breakthrough:'把注意力帶回當下可照顧的一件事，承認受傷，也允許修復開始。',message:'你不是傷痕本身；你是穿越它之後更完整的自己。',affirm:'我接納真實的自己，以復原與希望走向適合我的道路。'},
  {id:'ACC010',name:'天竺葵',en:'Geranium',latin:'Pelargonium graveolens',image:'ACC010 天竺葵.png',energy:'平衡型',element:'水',chakra:'心輪',keywords:['平衡','親密','滋養','接納','柔韌','界線'],gift:'你感受敏銳、擅長照顧關係，也有柔軟調整與修復連結的能力。',shadow:'你可能把對方的情緒當成自己的責任，過度介入，又擔心自己被忽略。',breakthrough:'辨認情緒的歸屬，清楚說出界線與期待；溫柔愛人，也要保留自己的中心。',message:'你可以溫柔地愛人，也可以清楚地保護自己。',affirm:'我接納真實的自己，以平衡與親密走向適合我的道路。'},
  {id:'ACC011',name:'杜松莓',en:'Juniper Berry',latin:'Juniperus communis',image:'ACC011 杜松莓.png',energy:'清理型',element:'風',chakra:'根輪',keywords:['淨化','界線','輕盈','決斷','保護','更新'],gift:'你辨識力強，善於斷捨離，也能從複雜資訊中迅速理出重點。',shadow:'累積太多責任與未完成事項時，你可能變得嚴格、切割過快，甚至孤立自己。',breakthrough:'列出優先順序，結束一件不再適合的事，為真正重要的人事物騰出空間。',message:'放下不屬於你的重量，路會變得更寬。',affirm:'我接納真實的自己，以淨化與界線走向適合我的道路。'},
  {id:'ACC012',name:'萊姆',en:'Lime',latin:'Citrus × aurantiifolia',image:'ACC012 萊姆.png',energy:'提振型',element:'火',chakra:'太陽神經叢',keywords:['活力','清晰','幽默','更新','果斷','輕快'],gift:'你反應敏捷、創意靈活，有能力讓停滯的氣氛重新流動。',shadow:'你可能追逐新鮮感卻沒有收尾，或用輕快與忙碌逃避較沉重的課題。',breakthrough:'選定一個目標，完成後再開新計畫；讓活力成為完成事情的力量。',message:'你的輕盈不是逃避，而是提醒生命仍有新的選擇。',affirm:'我接納真實的自己，以活力與清晰走向適合我的道路。'},
  {id:'ACC013',name:'山雞椒',en:'Litsea Cubeba',latin:'Litsea cubeba',image:'ACC013 山雞椒.png',energy:'振奮型',element:'火',chakra:'太陽神經叢',keywords:['喜悅','清楚','轉機','創意','俐落','希望'],gift:'你樂觀機敏、善於抓住重點，也能替低迷局面帶來轉機。',shadow:'急著解決問題時，你可能還沒真正聽懂需求，便用樂觀掩飾內在焦慮。',breakthrough:'先停下來深呼吸三次，再確認最核心的需求，讓清楚領先速度。',message:'你要找的出口，也許就在一次清楚的選擇裡。',affirm:'我接納真實的自己，以喜悅與清楚走向適合我的道路。'},
  {id:'ACC014',name:'依蘭依蘭',en:'Ylang Ylang',latin:'Cananga odorata',image:'ACC014 依蘭依蘭.png',energy:'感受型',element:'水',chakra:'臍輪',keywords:['感官','喜悅','親密','放鬆','創造','接納'],gift:'你富有藝術感與自然魅力，懂得享受生命，也能創造豐盛而柔美的氛圍。',shadow:'當感受過於強烈，你可能沉溺幻想、逃避現實，或讓情緒取代真實溝通。',breakthrough:'把一個渴望化成可說明、可執行的需求，用成熟選擇承接你的感受。',message:'允許自己感受喜悅，並用成熟的選擇承接它。',affirm:'我接納真實的自己，以感官與喜悅走向適合我的道路。'},
  {id:'ACC015',name:'穗甘松',en:'Spikenard',latin:'Nardostachys jatamansi',image:'ACC015 穗甘松.png',energy:'內觀型',element:'土',chakra:'頂輪',keywords:['臣服','寧靜','慈悲','放下','古老智慧','安住'],gift:'你具有深度內省與包容的力量，能沉著陪伴自己和他人走過低谷。',shadow:'你可能仍背負過多哀傷，退縮封閉、沉在過去，與現實及新的連結漸行漸遠。',breakthrough:'建立穩定的日常作息，讓身體帶你回到當下；放下不是遺忘，而是繼續生活。',message:'放下並非遺忘，而是讓愛換一種方式留在心中。',affirm:'我接納真實的自己，以臣服與寧靜走向適合我的道路。'},
  {id:'ACC016',name:'迷迭香',en:'Rosemary',latin:'Salvia rosmarinus',image:'ACC016 迷迭香.png',energy:'聚焦型',element:'風',chakra:'眉心輪',keywords:['清晰','記憶','專注','勇氣','紀律','啟動'],gift:'你頭腦敏捷、規劃力強，能快速啟動並推進重要任務。',shadow:'同時處理太多事會讓注意力碎裂；你也可能過度用腦、苛求效率而難以放鬆。',breakthrough:'關閉干擾，安排一段只做一件事的時間；答案在聚焦，而非更多資訊。',message:'答案不在更多資訊裡，而在你願意專注的那一件事。',affirm:'我接納真實的自己，以清晰與專注走向適合我的道路。'},
  {id:'ACC017',name:'乳香',en:'Frankincense',latin:'Boswellia sacra／Boswellia carterii',image:'ACC017 乳香.png',energy:'提升型',element:'風',chakra:'頂輪',keywords:['呼吸','信念','寬廣','靜心','整合','超越'],gift:'你擁有宏觀視野與內在穩定，能在紛亂中看見真正的核心。',shadow:'你可能想得高遠，卻以道理取代感受，尚未照顧眼前真實的情緒。',breakthrough:'從呼吸與身體感受開始，再決定下一步；讓理想與此刻的自己重新連線。',message:'當呼吸慢下來，你會記得自己比眼前困局更寬廣。',affirm:'我接納真實的自己，以呼吸與信念走向適合我的道路。'},
  {id:'ACC018',name:'安息香',en:'Benzoin',latin:'Styrax benzoin',image:'ACC018 安息香.png',energy:'安撫型',element:'土',chakra:'根輪',keywords:['安慰','歸屬','溫暖','滿足','承接','安全感'],gift:'你親和溫暖、善於安撫，能為自己與他人創造安心停靠的空間。',shadow:'害怕不舒服可能讓你依賴舒適圈、遲遲不開始，或用享受暫時避開壓力。',breakthrough:'先給自己足夠支持，再完成一個最小行動；安全感可以成為出發點。',message:'你可以先被安慰，再帶著安全感向前走。',affirm:'我接納真實的自己，以安慰與歸屬走向適合我的道路。'},
  {id:'ACC019',name:'丁香花苞',en:'Clove Bud',latin:'Syzygium aromaticum',image:'ACC019 丁香花苞.png',energy:'驅動型',element:'火',chakra:'根輪',keywords:['勇氣','熱情','保護','決斷','意志','啟動'],gift:'你意志堅定、行動果敢，能在關鍵時刻挺身而出並守護重要的人事物。',shadow:'你可能把所有問題都視為必須立刻攻克的戰場，因急躁或強勢而把壓力帶給身邊的人。',breakthrough:'先降低力道，判斷何時該推進、何時該等待；真正的力量也包含節制。',message:'你不必一直燃燒自己，穩定的火也能照亮道路。',affirm:'我接納真實的自己，以勇氣與熱情走向適合我的道路。'},
  {id:'ACC020',name:'甜橙',en:'Orange Sweet',latin:'Citrus × sinensis',image:'ACC020 甜橙.png',energy:'喜悅型',element:'火',chakra:'臍輪',keywords:['快樂','豐盛','親和','童心','分享','放鬆'],gift:'你樂觀親切、凝聚力強，能讓身邊的人自在地做自己。',shadow:'你可能為了維持氣氛而逃避嚴肅問題、取悅群體，也因此缺乏持續力。',breakthrough:'用友善但直接的方式說出真話；真正的喜悅，也能容納不舒服的情緒。',message:'喜悅不是獎賞，而是你此刻就能允許的生命力。',affirm:'我接納真實的自己，以快樂與豐盛走向適合我的道路。'},
  {id:'ACC021',name:'薑',en:'Ginger',latin:'Zingiber officinale',image:'ACC021 薑.png',energy:'推進型',element:'火',chakra:'太陽神經叢',keywords:['行動','膽識','溫暖','流動','冒險','突破'],gift:'你敢於嘗試、反應迅速，能將想法真正推向行動。',shadow:'你可能一面等待百分之百確定才開始，一面又在行動時太過衝動、忽略風險。',breakthrough:'接受七成把握，先做一個可逆的小實驗；勇敢是在評估後仍願意跨步。',message:'你已經準備得比想像中更多，現在需要的是第一步。',affirm:'我接納真實的自己，以行動與膽識走向適合我的道路。'},
  {id:'ACC022',name:'大西洋雪松',en:'Cedarwood Atlas',latin:'Cedrus atlantica',image:'ACC022 大西洋雪松.png',energy:'穩固型',element:'土',chakra:'根輪',keywords:['結構','尊嚴','界線','耐力','領導','承擔'],gift:'你沉著有原則，擅長建立制度，也能長期守護真正重要的目標。',shadow:'凡事依靠控制會讓你難以信任他人的方法，顯得僵化、不易示弱。',breakthrough:'明確說出標準，再授權對方完成；穩固的界線不必是一道高牆。',message:'你的界線不必像高牆，也可以是一扇清楚開關的門。',affirm:'我接納真實的自己，以結構與尊嚴走向適合我的道路。'},
  {id:'ACC023',name:'黑胡椒',en:'Black Pepper',latin:'Piper nigrum',image:'ACC023 黑胡椒.png',energy:'催化型',element:'火',chakra:'太陽神經叢',keywords:['自律','動力','膽識','專注','耐力','改變'],gift:'你能直面挑戰、執行力強，也擅長把長久的停滯轉化成實際進度。',shadow:'競爭心與急於推進的壓力，可能讓你只靠意志硬撐，也不自覺催促他人。',breakthrough:'把目標拆小，安排推進與休息的節奏；穩定的小步同樣具有改變的熱度。',message:'不要低估小步累積的熱度，它足以改變整條路。',affirm:'我接納真實的自己，以自律與動力走向適合我的道路。'},
  {id:'ACC024',name:'廣藿香',en:'Patchouli',latin:'Pogostemon cablin',image:'ACC024 廣藿香.png',energy:'整合型',element:'土',chakra:'根輪',keywords:['真實','感官','豐盛','扎根','自由','整合'],gift:'你忠於自我、感官敏銳，能接納非主流與多樣性，也能替被排斥的部分找回價值。',shadow:'你可能為了證明不同而反射性反抗，拒絕其實適合自己的建議，或用固執保護脆弱。',breakthrough:'分辨自由選擇與反射性反抗的差別；做自己不必靠對抗，也能靠穩定而負責的選擇。',message:'你不需要符合所有期待，只需要為自己的選擇負責。',affirm:'我接納真實的自己，以真實與自由走向適合我的道路。'},
  {id:'ACC025',name:'甜羅勒',en:'Basil Sweet',latin:'Ocimum basilicum',image:'ACC025 甜羅勒.png',energy:'整理型',element:'風',chakra:'眉心輪',keywords:['清晰','決策','秩序','靈感','效率','辨識'],gift:'你邏輯清楚、善於統整，能在資訊過載時釐清重點並做出決策。',shadow:'反覆比較選項會讓你神經緊繃、過度分析，也可能對自己與他人的速度失去耐心。',breakthrough:'設定決策期限，依最重要的三項標準做選擇；你不需要完美答案，只需要此刻最誠實的答案。',message:'你不需要找到完美答案，只需要做出此刻最誠實的選擇。',affirm:'我接納真實的自己，以清晰與決策走向適合我的道路。'},
  {id:'ACC026',name:'甜馬鬱蘭',en:'Marjoram Sweet',latin:'Origanum majorana',image:'ACC026 甜馬鬱蘭.png',energy:'舒緩型',element:'土',chakra:'心輪',keywords:['休息','安定','陪伴','節制','柔和','歸家'],gift:'你耐心體貼、善於調和節奏，能讓自己與身邊的人感到可靠而安心。',shadow:'你可能因為怕麻煩別人而默默承受，過度退讓，把自己的需求與渴望縮得太小。',breakthrough:'提出一個具體請求，讓支持有機會進來；休息是恢復力量，不是放棄前進。',message:'你不必耗盡自己，才有資格停下來休息。',affirm:'我接納真實的自己，以休息與安定走向適合我的道路。'},
  {id:'ACC027',name:'胡蘿蔔籽',en:'Carrot Seed',latin:'Daucus carota',image:'ACC027 胡蘿蔔籽.png',energy:'更新型',element:'土',chakra:'臍輪',keywords:['滋養','更新','耐心','成熟','自信','重整'],gift:'你懂得長期培養、善於修復細節，也有看見尚未成熟事物之潛力的眼光。',shadow:'進度焦慮可能讓你反覆檢查、過度挑剔，甚至太早否定尚在形成中的成果。',breakthrough:'設定觀察週期，在期限前停止反覆修改；成長有自己的節奏，需要的是滋養而非催促。',message:'別急著判斷尚未完成的自己，你正在形成新的樣子。',affirm:'我接納真實的自己，以滋養與更新走向適合我的道路。'}
];

const positions=[
  {label:'第一張｜此刻的你',title:'個人狀態',field:'gift',intro:c=>`「${c.energy}」正在你身上運作。`},
  {label:'第二張｜內在課題',title:'困擾與問題',field:'shadow',intro:c=>`這張牌照見的是「${c.keywords[1]}」背後尚未被安放的部分。`},
  {label:'第三張｜前行之光',title:'方向與指引',field:'breakthrough',intro:c=>`讓「${c.keywords[0]}」成為你接下來的導航。`}
];
let current=[];
const $=s=>document.querySelector(s);
function show(id){['#intro','#ritual','#reading'].forEach(s=>$(s).classList.toggle('hidden',s!==id));window.scrollTo({top:0,behavior:'smooth'})}
function sample(){const pool=[...cards];current=[];while(current.length<3){current.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0])}render();show('#reading')}
function render(){
  $('#cards').innerHTML=current.map((c,i)=>{const p=positions[i];return `<article class="reading-card"><div class="card-image"><img src="${c.image}" alt="${c.name}精油人格牌卡"></div><div class="card-body"><span class="position">${p.label}</span><h3>${c.name} <small>${c.en}</small></h3><p class="latin">${c.latin} · ${c.element}元素 · ${c.chakra}</p><div class="reading-block"><h4>${p.title}</h4><p>${p.intro(c)}${c[p.field]}</p></div><div class="reading-block"><h4>牌卡訊息</h4><p>${c.message}</p></div><div class="keywords">${c.keywords.slice(0,4).map(k=>`<span>${k}</span>`).join('')}</div></div></article>`}).join('');
  const [a,b,c]=current;
  $('#synthesis').innerHTML=`<p class="eyebrow">INTEGRATED MESSAGE</p><h3>三牌整合｜從「${a.keywords[0]}」穿越「${b.keywords[1]}」，走向「${c.keywords[0]}」</h3><p>你並不是沒有力量，而是此刻需要用更貼近自己的方式前進。${a.name}提醒你看見已有的資源；${b.name}指出真正消耗你的內在拉扯；${c.name}則邀請你把答案落在一個具體、溫柔而可持續的行動上。今天不必解決全部，只要完成下一個誠實的小步驟。</p><p class="affirmation">今日肯定語：${c.affirm}</p>`;
}
function copyReading(){const text=current.map((c,i)=>`${positions[i].label}｜${c.name}\n${positions[i].intro(c)}${c[positions[i].field]}\n${c.message}`).join('\n\n')+`\n\n今日肯定語：${current[2].affirm}\n\n（此牌卡為自我覺察工具，不取代專業建議。）`;navigator.clipboard.writeText(text).then(()=>{const b=$('#copyBtn');b.textContent='已複製 ✓';setTimeout(()=>b.textContent='複製本次指引',1800)}).catch(()=>alert('瀏覽器未允許自動複製，請手動選取內容。'))}
$('#beginBtn').addEventListener('click',()=>show('#ritual'));$('#drawBtn').addEventListener('click',sample);$('#againBtn').addEventListener('click',()=>show('#ritual'));$('#restartBtn').addEventListener('click',()=>show('#ritual'));$('#copyBtn').addEventListener('click',copyReading);
